name: Update Dependencies

on:
  schedule:
# Runs at 00:00 on Wednesday
    - cron: '0 0 * * 3'
  workflow_dispatch:

jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Update dependencies
        run: |
          npm install -g npm-check-updates
          ncu -u --packageFile package.json
          npm install

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "chore: update npm dependencies"
          body: |
            Automated dependency updates via [npm-check-updates](https://github.com/raineorshine/npm-check-updates).

            This PR was created by the [Update Dependencies](../../actions/workflows/package_update.yml) workflow.
          branch: "package-update/auto"
          author: "Ashik Kumar <ashikkumar23@gmail.com>"
          labels: "dependencies"
